config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users,
  ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'families#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :families
  resources :users do
    resources :recipes do
      resources :ingredients
      resources :comments , only: [:new, :create]
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :family, :host, :photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :users , dependent: :destroy
  has_many :recipes, through: :users , dependent: :destroy
  has_one_attached :photo

 # Need valition here
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true
  has_many :ingredients, dependent: :destroy
  has_one_attached :photo
  has_many :comments, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :family
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  # Redirection after sign_in (User versus Admin)
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(User)
      user_recipes_path(resource_or_scope)
    elsif resource_or_scope.is_a?(AdminUser)
      admin_dashboard_path(resource_or_scope)
    end
  end

  # For additional fields in app/views/devise/registrations/new.html.erb
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name , :password, :family_id])
  end

  def user_connected
    # Look up the current user based on user_id in the session cookie:
    #TIP: The ||= part ensures this helper doesn't hit the database every time a user hits a web page. It will look it up once, then cache it in the @current_user variable.
    #This is called memoization and it helps make our app more efficient and scalable.
    @user_connected ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :except => [:new, :create],
                :set_user,
                :find_recipe, :only => [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.recipe = @recipe
    @comment.save

    redirect_to user_recipe_path(@user,@recipe)
  end

  private

  def comment_params
    params.require(:comment).permit(
      :name,
      :comment_description,
      :recipe_id
      )
  end

  def set_user
    @user = current_user
  end

  def find_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end


end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  # Ajouter une "fonction pour etre sur que l user est connecte pr acceder a cette page
  before_action :authenticate_user!

  def show
    @family = Family.find(params[:id])
  end

  def index
    @families = Family.all
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(params_family)
    @family.save

    redirect_to family_path(@family)
  end

private

  def params_family
    params.require(:family).permit(
      :name,
      :photo
      )
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_user, :set_recipe, expect: [:index]

  def index
    @ingredients = Ingredient.all
  end


  def new
    @ingredient = Ingredient.new
    @ingredients = Ingredient.where(recipe_id: @recipe_id)
  end

  def create
    @ingredient = Ingredient.new(params_ingredient)
    @ingredient.recipe = @recipe
    @ingredient.save

    redirect_to new_user_recipe_ingredient_path(@user,@recipe)
  end



  private

  def params_ingredient
    params.require(:ingredient).permit(
      :name,
      :quantity,
      :measure,
    )
  end

  def set_user
    @user = current_user
  end

  def set_recipe
    @recipe = Recipe.last
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user, expect: [:show]


  def index
    @first_five_current_user_recipes = current_user.recipes.first(5)
    @family_recipe = current_user.family.recipes
    @results = []

    if params[:query].present?
      sql_query = " \
        recipes.category ILIKE :query \
      "
      @queried_category = params[:query]
      @result_arr = Recipe.where(sql_query, query: "%#{params[:query]}%")
    else
      @result_arr = current_user.family.recipes
    end


  end

  def show
    @user = User.find(params[:user_id])
    @recipe = Recipe.friendly.find(params[:id])
    @ingredients = Ingredient.where(recipe_id: @recipe.id)

    @recipe_review_url = "https://lesrecettesdenosmamies.herokuapp.com/users/#{@user.id}/recipes/#{@recipe.id}"

    @comments_counter = @recipe.comments.count
  end


  def new
    @recipe = Recipe.new
  end


  def create
    @recipe = Recipe.new(params_recipe)
    @recipe.user = @user
    @recipe.save

    redirect_to new_user_recipe_ingredient_path(@user,@recipe)
  end

  private

  def params_recipe
    params.require(:recipe).permit(
      :category,
      :description,
      :minute,
      :person,
      :name,
      :photo,
      :user
    )
  end

  def set_user
    @user = current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user! , :set_user

  def show
  end

  def edit
  end

  def update
    @user.update(comment_params)
    redirect_to user_path(@user)
  end




  private

  def comment_params
    params.require(:user).permit(
      :name,
      :family,
      :email
      )
  end

  def set_user
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  #Message pour pop-up

  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/comments/new.html.erb
<%= simple_form_for ([@user, @recipe, @comment]) do |f| %>
  <%= f.input :name, input_html: { placeholder: "Votre nom " } %>
  <%= f.input :comment_description,
              as: :text,
              input_html: { placeholder: "Votre avis ici " } %>
  <%= f.button :submit, 'Je commente ! '%>
<% end %>

app/views/families/index.html.erb
<!-- Families index = After Login page  -->


<!-- Red container  -->
<div class="container-home-red">
  <!-- Se deconnecter bouton  -->
  <div class="logo">
    <span style="width:150px"></span>
    <%= image_tag "logo_transparent.png", alt: "alttext" %>
    <div class="btn-logout">
      <%= link_to destroy_user_session_path, method: :delete do %>
        Se deconnecter
      <% end %>
    </div>
  </div>


  <div class="description-home">
    <h1> Bienvenue sur <span> Les recettes de nos mamies ! </span> </h1>
  </div>
  <div class="description-text">
    <p>Ce site vous permet de partager en famille vos meilleures recettes :
    celles de vos mamies, de votre maman, de vos frères & soeurs...
    Retrouvez-les facilement et n'hésitez pas à les partager et à les commenter ! </p>
  </div>
</div>

  <div class="btn-container">
    <!-- Bouton se connecter  -->
    <% if current_user == nil %>
      <svg id="stroke" xmlns="http://www.w3.org/2000/svg" width="0" height="0">
        <defs>
          <path id="line" d="M2 2c49.7 2.6 100 3.1 150 1.7-46.5 2-93 4.4-139.2 7.3 45.2-1.5 90.6-1.8 135.8-.6" fill="none" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>
        </defs>
      </svg>
      <a class="btn btn-login" href= "./users/sign_in" > Se connecter
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
      </a>

    <% else %>

      <!-- Mes recettes -->
      <svg id="stroke" xmlns="http://www.w3.org/2000/svg" width="0" height="0">
        <defs>
          <path id="line" d="M2 2c49.7 2.6 100 3.1 150 1.7-46.5 2-93 4.4-139.2 7.3 45.2-1.5 90.6-1.8 135.8-.6" fill="none" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>
        </defs>
      </svg>
      <a class="btn btn-login" href= "./users/:id/recipes" > Mes recettes
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
      </a>
    <% end %>
  </div>

app/views/families/new.html.erb
  <h1><strong>Votre Famille </strong></h1></div>

  <div class="container">
    <%= simple_form_for @family do |f| %>
      <%= f.error_notification %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn btn-primary font-weight-bold" %>
    <% end %>
  </div>

app/views/families/show.html.erb
<%= @family.name %>



<div class="btn-logout">
  <%= link_to families_path do %>
    Retour
  <% end %>
</div>

app/views/familles/index.html.erb
<!-- Red container  -->
<div class="container-home-red">


  <div class="logo">
    <%= image_tag "logo_transparent.png", alt: "alttext" %>
      <div class="btn-logout">
        <%= link_to destroy_user_session_path, method: :delete do %>
          Se deconnecter
        <% end %>
      </div>
  </div>

  <div class="description-home">
    <h1> Bienvenue sur <span> Les recettes de nos mamies ! </span> </h1>
  </div>
  <div class="description-text">
    <p>Nous avons crees ce site pour vous permettre de partager, en famille, vos meilleures recettes.
    Celles de vos mamies, de votre maman, de vos freres & soeurs...
    Retrouvez facilement leurs meilleures recettes, et n hesitez pas a les commenter ! </p>
  </div>

    <!-- Create a famille, se conncter and creer a profil bouton  -->
    <div class="btn-container">
      <svg id="stroke" xmlns="http://www.w3.org/2000/svg" width="0" height="0">
        <defs>
          <path id="line" d="M2 2c49.7 2.6 100 3.1 150 1.7-46.5 2-93 4.4-139.2 7.3 45.2-1.5 90.6-1.8 135.8-.6" fill="none" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>
        </defs>
      </svg>
      <a class="btn " href= "./familles/new" >Creer une famille
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
      </a>

      <svg id="stroke" xmlns="http://www.w3.org/2000/svg" width="0" height="0">
        <defs>
          <path id="line" d="M2 2c49.7 2.6 100 3.1 150 1.7-46.5 2-93 4.4-139.2 7.3 45.2-1.5 90.6-1.8 135.8-.6" fill="none" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>
        </defs>
      </svg>
      <a class="btn btn-login" href= "./users/sign_in" > Se connecter
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
      </a>

         <svg id="stroke" xmlns="http://www.w3.org/2000/svg" width="0" height="0">
        <defs>
          <path id="line" d="M2 2c49.7 2.6 100 3.1 150 1.7-46.5 2-93 4.4-139.2 7.3 45.2-1.5 90.6-1.8 135.8-.6" fill="none" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>
        </defs>
      </svg>
      <a class="btn" href= "./users/sign_up" >S'inscrire
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
        <svg class="button-stroke" viewBox="0 0 154 13">
          <use href="#line"></use>
        </svg>
      </a>
    </div>
 </div>


  <!-- Carte container  -->
      <div class="description-famille">
        Les familles deja inscrites
      </div>

      <div class="card-container">
        <% @familles.each do |famille| %>
          <%= link_to famille_path(famille) do %>
            <div class="card-category">
              <%= cl_image_tag famille.photo.key, class: "card-category"%>
             <div class="card-text"><%= famille.name %> </div>
            </div>
            <% end %>
        <% end %>
      </div>

app/views/familles/new.html.erb
  <h1><strong>Votre Famille </strong></h1></div>

  <div class="container">
    <%= simple_form_for @famille do |f| %>
      <%= f.error_notification %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn btn-primary font-weight-bold" %>
    <% end %>
  </div>

app/views/ingredients/new.html.erb
<div class="container">

  <h1> <%= @recipe.name %> </h1>

  <h3>Liste des ingrédients</h3>

  <% @recipe.ingredients.each do |ingredient| %>
    </li> <%= ingredient.quantity %> <%= ingredient.measure %> <%= ingredient.name %> </li>
  <% end %>



  <div class="container-form">
    <%= simple_form_for [@user, @recipe, @ingredient] do |f| %>
      <%= f.error_notification %>
      <%= f.input :name , label: "Ingrédient"%>
      <%= f.input :measure,
                  label: "Unité",
                  collection: ["g","l","-","cl","kg","cuillère(s) à café", "cuillère(s) à soupe", "pincée(s)", "sachet(s)"],
                  hint: 'Pour les oeufs ou les produits entiers, utilisez le "-"' %>
      <%= f.input :quantity, label: "Quantité"%>
      <%= f.button :submit %>
    <% end %>
  </div>
   <div class="btn-logout">
    <%= link_to user_recipe_path(@user,@recipe) do %>
      Valider la recette
    <% end %>
  </div>
</div>

app/views/layouts/_home.html.erb
<!-- Red container  -->
<div class="container-home-red">
  <div class="logo">
    <span style="width:150px"></span>

    <%= image_tag "logo_transparent.png", alt: "alttext" %>

    <div class="btn-logout">
      <%= link_to new_user_registration_path do %>
        S'inscrire
      <% end %>
    </div>

  </div>




  <div class="description-home">
    <h1> Bienvenue sur <span> Les recettes de nos mamies ! </span> </h1>
  </div>
  <div class="description-text">
    <p>Ce site pour vous permettre de partager, en famille, vos meilleures recettes.
    Celles de vos mamies, de votre maman, de vos freres & soeurs...
    Retrouvez facilement leurs meilleures recettes, et n'hesitez pas a les commenter ! </p>
  </div>


    <div class="btn-container">
      <!-- tu as des methodes user.is_sing_in? ou qqchose comme ca -->
      <% if current_user == nil %>
        <svg id="stroke" xmlns="http://www.w3.org/2000/svg" width="0" height="0">
          <defs>
            <path id="line" d="M2 2c49.7 2.6 100 3.1 150 1.7-46.5 2-93 4.4-139.2 7.3 45.2-1.5 90.6-1.8 135.8-.6" fill="none" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>
          </defs>
        </svg>
        <a class="btn btn-login" id="modal-button" href= "#" > Se connecter
          <svg class="button-stroke" viewBox="0 0 154 13">
            <use href="#line"></use>
          </svg>
          <svg class="button-stroke" viewBox="0 0 154 13">
            <use href="#line"></use>
          </svg>
        </a>
      <% else %>
        <!-- Mes recettes -->
        <svg id="stroke" xmlns="http://www.w3.org/2000/svg" width="0" height="0">
          <defs>
            <path id="line" d="M2 2c49.7 2.6 100 3.1 150 1.7-46.5 2-93 4.4-139.2 7.3 45.2-1.5 90.6-1.8 135.8-.6" fill="none" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>
          </defs>
        </svg>
        <a class="btn btn-login" href= "./users/:id" > Mes recettes
          <svg class="button-stroke" viewBox="0 0 154 13">
            <use href="#line"></use>
          </svg>
          <svg class="button-stroke" viewBox="0 0 154 13">
            <use href="#line"></use>
          </svg>
        </a>
      <% end %>
    </div>
</div>


        <!-- Carte container  -->
        <!-- Indentation -->

  <div class="second-part">
    <div class="description-famille">
      Comment ca marche ?
    </div>
    <div class="tuto">
      <div class="card-category">
        1. <br> Je m'inscris
      </div>
      <div class="arrow">
        <%= image_tag "smallarrow.png", alt: "alttext" %>
      </div>
      <div class="card-category">
        2. <br> J'ajoute mes recettes
      </div>
      <div class="arrow">
        <%= image_tag "smallarrow.png", alt: "alttext" %>
      </div>
      <div class="card-category">
        3. <br> Je partage
      </div>
      <div class="arrow">
        <%= image_tag "smallarrow.png", alt: "alttext" %>
      </div>
      <div class="card-category">
        4. <br> Je consulte les recettes !
      </div>
    </div>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">





    <title>Les Recettes de Mamie</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <!-- Home btn -->


    <%= yield %>

    <%= render 'layouts/messages' %>


    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/recettes/new.html.erb
  <h1><strong>Votre Recette </strong></h1></div>

  <div class="container">
    <%= simple_form_for [@user, @recette] do |f| %>
      <%= f.error_notification %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :ingredient %>
      <%= f.button :submit %>
    <% end %>
  </div>

app/views/recipes/index.html.erb
<div class ="container" data-no-turbolink>
<!-- Link for user page -->
 <h1> Hello <%= link_to @user.name , user_path(@user) %> </h1>

  <!-- Recette creer par l'utilisateur -->
  <div class="card-recipe">
    <h3>Mes recettes </h3>
      <div class="card-container">
        <% @first_five_current_user_recipes.each do |recipe| %>
          <%= link_to user_recipe_path(@user,recipe) do %>
            <!-- Picture  -->
            <div class="card-category ml-2">
              <% if recipe.photo.attached? %>
                <%= cl_image_tag recipe.photo.key, class: "card-category"%>
              <% else %>
                <img class="card-category" src="https://semantic-ui.com/images/wireframe/image.png" >
              <% end %>
              <div class="card-text"><%= recipe.name %> </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>

  <!-- Recette d'une meme famille -->
  <div class="card-recipe">
    <h3>Les recettes de ma famille</h3>
    <!-- Methode recherche (no CSS yet, via radio button) -->
     <div>
        <%= form_tag user_recipes_path, method: :get do %>
        <%= radio_button_tag :query, "Dessert",params[:query]%> Dessert
        <%= radio_button_tag :query, "Plat" %> Plat
        <%= radio_button_tag :query,"Entre" %> Entre
        <div>
        <%= submit_tag "Search", class: "btn-logout" %>
        <% end %>
        </div>
      </div>

      <!-- Lien vers la recette -->
      <% @result_arr.each do |recipe|%>
        <li>
          <%= link_to user_recipe_path(@user,recipe) do %>  <%= recipe.name %> <% end %>
          par
          <i> <%= recipe.user.name %> </i>
        </li>
      <% end %>
  </div>


  <!-- Ajouter une recette -->
  <%= link_to new_user_recipe_path(@user, @recipe) do %>
    <div class="btn btn-primary">
      Ajouter une recette
    </div>
  <% end %>

  <!-- Se deconnecter  -->
  <div class="btn-logout">
    <%= link_to destroy_user_session_path, method: :delete do %>
      Se deconnecter
    <% end %>
  </div>



</div>

app/views/recipes/new.html.erb
<div class= "container">

  <h1><strong> Votre Recette </strong></h1>

  <div class="container">
    <%= simple_form_for [@user, @recipe] do |f| %>
      <%= f.error_notification %>
      <%= f.input :name %>
      <%= f.input :description,
                  label: "Préparation", as: :trix_editor %>
      <%= f.input :category,
                  as: :radio_buttons,
                  collection: [ "Entrée", "Plat", "Dessert" ] %>
      <%= f.input :minute, label: "Temps de préparation en min" %>
      <%= f.input :person, label: "Pour combien de personne(s) ?" %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <h1> <%= @recipe.name %> </h1>
  <i>  <%= @recipe.person %> personne(s) - <%= @recipe.minute %> min </i>
  <h6> <b> <%= @recipe.category %> </b></h6>

    <% if @recipe.photo.attached? %>
      <%= cl_image_tag @recipe.photo.key, class: "card-category"%>
    <% else %>
      <img class="card-category" src="https://semantic-ui.com/images/wireframe/image.png" >
    <% end %>
    <div class="container-ingredient">
      <h3>Liste des ingredients</h3>
      <%  @ingredients.each do |ingredient|%>
       <li> <%= ingredient.quantity %> - <%= ingredient.measure %> - <%= ingredient.name  %> </li>
      <% end %>
    </div>

  ================================== <br>

  <h3>Préparation </h3>

  <br>

  <%= sanitize @recipe.description %>

  <div class="bottom-btn">
    <!-- Block to share whatapps link -->
    <div class="btn-logout">
      <%= link_to user_recipes_path do %>
        Retour
      <% end %>
    </div>
    <div class="btn-logout">
      <a href="whatsapp://send?text= <%= @recipe_review_url %>"> <i class="fab fa-whatsapp"></i> Partager</a>
    </div>
  </div>
</div>


    <!-- Block to add comments -->
    <div class="container">
      <div class="comment-logic">
        <% if @comments_counter > 0 %>
          <h5>Commentaire(s)</h5>
        <% end %>
      </div>


      <% @recipe.comments.each do |comment| %>
        <div class="d-flex flex-column flex-end">
          <div class="d-flex justify-content-between info-comment">
            <p class="mb-0 comment-name"><%= comment.name %></p>
            <p class="mb-0 comment-date"><%= comment.created_at.strftime('%d %b %Y') %></p>
          </div>
          <p class="comment-description">" <%= comment.comment_description%>"</p>
        </div>
      <% end %>

      <% if current_user.nil? %>
        <%= link_to "Laisser un commentaire", new_user_recipe_comment_path(@user,@recipe), class: "btn-review-comment"%>
      <% elsif current_user != @recipe.user %>
        <%= link_to "Laisser un commentaire", new_user_recipe_comment_path(@user,@recipe), class: "btn-review-comment"%>
      <% end %>
    </div>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :family %>
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" }%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Changer" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <br> Bonjour, <%= @user.name %>
  <br> email : <%= @user.email %>
  <br>
<!-- Mettre les differents option une edit -->
  <%= link_to edit_user_path(@user) do %>
    <div class="btn btn-primary">
      Changer mes infos
    </div>
  <% end %>



  <br>
  <%= link_to user_recipes_path(@user) do %>
    <div class="btn btn-logout">
      Retour
    </div>
  <% end %>

 </div>